/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PalmRouteImport } from './routes/palm'
import { Route as MintRouteImport } from './routes/mint'
import { Route as FortuneRouteImport } from './routes/fortune'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AstrologyRouteImport } from './routes/astrology'
import { Route as IndexRouteImport } from './routes/index'

const PalmRoute = PalmRouteImport.update({
  id: '/palm',
  path: '/palm',
  getParentRoute: () => rootRouteImport,
} as any)
const MintRoute = MintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => rootRouteImport,
} as any)
const FortuneRoute = FortuneRouteImport.update({
  id: '/fortune',
  path: '/fortune',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyRoute = AstrologyRouteImport.update({
  id: '/astrology',
  path: '/astrology',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/astrology': typeof AstrologyRoute
  '/dashboard': typeof DashboardRoute
  '/fortune': typeof FortuneRoute
  '/mint': typeof MintRoute
  '/palm': typeof PalmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/astrology': typeof AstrologyRoute
  '/dashboard': typeof DashboardRoute
  '/fortune': typeof FortuneRoute
  '/mint': typeof MintRoute
  '/palm': typeof PalmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/astrology': typeof AstrologyRoute
  '/dashboard': typeof DashboardRoute
  '/fortune': typeof FortuneRoute
  '/mint': typeof MintRoute
  '/palm': typeof PalmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/astrology' | '/dashboard' | '/fortune' | '/mint' | '/palm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/astrology' | '/dashboard' | '/fortune' | '/mint' | '/palm'
  id:
    | '__root__'
    | '/'
    | '/astrology'
    | '/dashboard'
    | '/fortune'
    | '/mint'
    | '/palm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AstrologyRoute: typeof AstrologyRoute
  DashboardRoute: typeof DashboardRoute
  FortuneRoute: typeof FortuneRoute
  MintRoute: typeof MintRoute
  PalmRoute: typeof PalmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/palm': {
      id: '/palm'
      path: '/palm'
      fullPath: '/palm'
      preLoaderRoute: typeof PalmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mint': {
      id: '/mint'
      path: '/mint'
      fullPath: '/mint'
      preLoaderRoute: typeof MintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fortune': {
      id: '/fortune'
      path: '/fortune'
      fullPath: '/fortune'
      preLoaderRoute: typeof FortuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology': {
      id: '/astrology'
      path: '/astrology'
      fullPath: '/astrology'
      preLoaderRoute: typeof AstrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AstrologyRoute: AstrologyRoute,
  DashboardRoute: DashboardRoute,
  FortuneRoute: FortuneRoute,
  MintRoute: MintRoute,
  PalmRoute: PalmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
